### ISSUE TITLE
[Intro to iOS] Assignment 3 - Yelp app complete

### ISSUE THREAD

**Issue by ewb2123** [ewb2123/Yelp#1]
My app is complete. Please review :) /cc @codepathreview

**Comment by minhchau273** [comment]
Hi Elijah,
You didn't complete `search` feature. Please update asap because this is a required functionality. In this assignment, you have to call the api to search the restaurants.
Thanks.

**Comment by chieger** [comment]
Hi Elijah,
We have not heard from you since Chau's comment 2 days ago, and the submission date was 3 days ago. 

**In order to receive credit for this assignment, you need to add the updates mentioned above in Chau's comment by the end of the day today**

Best,
Charlie Hieger
CodePath University Dean

**Comment by ewb2123** [comment]
Hi Chau and Charlie,

I have just completed the search functionality and pushed the update to the repository. I apologize for the delay. 

Elijah Bullard

**Comment by minhchau273** [comment]
:+1: Nice work! This primary challenge of this homework was to learn how to use AutoLayout to build adaptive UI's that work across many different screen sizes and orientations. If you haven't already, we recommend going back and running your homework again while rotating the device / simulator to ensure your AutoLayout constraints function as expected.

### Some small comments:
- Nice work specifying the Auto Layout constraints.
- The auto layout may not work well. The name and category labels are truncated in some cells.
  <img width="316" alt="screen shot 2016-02-18 at 8 29 18 pm" src="https://cloud.githubusercontent.com/assets/12395213/13144652/6db5c364-d67e-11e5-8b4d-6f00c55ad47e.png">
- That would be nice is if you handled the "no results" case gracefully, as well as didn't show empty gray lines when there is only 1 result.
- For now, you only search within the current restaurants. In this assignment, you have to call the api to search the restaurants.

We have a detailed [Project 3 Feedback Guide](http://courses.codepath.com/snippets/ios_university/feedback_guides/project_3_feedback.md) which covers the best practices for implementing this assignment. Read through the feedback guide point-by-point to determine ways you might be able to improve your submission. You should consider going back and implementing these improvements as well. Keep in mind that one of the most important parts of iOS development is learning the correct patterns and conventions.

If you have any particular questions about the assignment or the feedback, feel free to reply here or email us at universitysupport@codepath.com.
